DROP TABLE DEPT IF EXISTS;
DROP TABLE EMP IF EXISTS;
DROP TABLE JOB IF EXISTS;

CREATE TABLE DEPT (	DEPTNO NUMBER , DNAME VARCHAR2(255  ),LOC VARCHAR2(255  ), CONSTRAINT PK_DEPT PRIMARY KEY (DEPTNO));
 
CREATE TABLE EMP   (	EMPNO NUMBER , 
	COMM FLOAT , 
	ENAME VARCHAR(255 ), 
	HIREDATE DATE, 
	SAL FLOAT , 
	DEPTNO NUMBER , 
	JOBNO NUMBER , 
	JOB VARCHAR(255) 
   , CONSTRAINT PK_EMP  PRIMARY KEY (EMPNO));

  CREATE TABLE JOB 
   (	JOBNO NUMBER , 
	JOB_TITLE VARCHAR(255) , 
	MAX_SALARY FLOAT , 
	MIN_SALARY FLOAT 
  , CONSTRAINT PK_JOB   PRIMARY KEY (JOBNO));
 
 
    