DROP TABLE DEPT IF EXISTS;
DROP TABLE EMP IF EXISTS;
DROP TABLE JOB IF EXISTS;

CREATE TABLE DEPT (	DEPTNO NUMBER , DNAME VARCHAR2(255  ),LOC VARCHAR2(255  ), CONSTRAINT PK_DEPT PRIMARY KEY (DEPTNO));
 

CREATE TABLE EMP (EMPNO NUMBER(10) NOT NULL, COMM FLOAT(126), ENAME VARCHAR2(255), HIREDATE DATE, SAL FLOAT(126), DEPTNO NUMBER(10), JOBNO NUMBER(10), JOB VARCHAR2(255),
PRIMARY KEY (EMPNO) );

  CREATE TABLE JOB 
   (	JOBNO NUMBER , 
	JOB_TITLE VARCHAR(255) , 
	MAX_SALARY FLOAT , 
	MIN_SALARY FLOAT 
  , CONSTRAINT PK_JOB   PRIMARY KEY (JOBNO));
 
 INSERT INTO EMP (EMPNO, COMM, ENAME, HIREDATE, SAL, DEPTNO, JOBNO, JOB) VALUES (128, null, '滾滾1', null, null, 2, 2, null);
INSERT INTO EMP (EMPNO, COMM, ENAME, HIREDATE, SAL, DEPTNO, JOBNO, JOB) VALUES (127, null, '凱莉12', null, null, 2, 2, null);
INSERT INTO EMP (EMPNO, COMM, ENAME, HIREDATE, SAL, DEPTNO, JOBNO, JOB) VALUES (129, null, 'nn', null, null, 2, 2, null);
INSERT INTO EMP (EMPNO, COMM, ENAME, HIREDATE, SAL, DEPTNO, JOBNO, JOB) VALUES (130, null, '安安1', null, null, 2, 2, null);

    