--------------------------------------------------------
--  �w�إ��ɮ� - �P���G-����-07-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table DEPT
--------------------------------------------------------

  CREATE TABLE "HR"."DEPT" 
   (	"DEPTNO" NUMBER(10,0), 
	"DNAME" VARCHAR2(255 BYTE), 
	"LOC" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EMP
--------------------------------------------------------

  CREATE TABLE "HR"."EMP" 
   (	"EMPNO" NUMBER(10,0), 
	"COMM" FLOAT(126), 
	"ENAME" VARCHAR2(255 BYTE), 
	"HIREDATE" DATE, 
	"SAL" FLOAT(126), 
	"DEPTNO" NUMBER(10,0), 
	"JOBNO" NUMBER(10,0), 
	"JOB" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table JOB
--------------------------------------------------------

  CREATE TABLE "HR"."JOB" 
   (	"JOBNO" NUMBER(10,0), 
	"JOB_TITLE" VARCHAR2(255 BYTE), 
	"MAX_SALARY" FLOAT(126), 
	"MIN_SALARY" FLOAT(126)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into HR.DEPT
SET DEFINE OFF;
Insert into HR.DEPT (DEPTNO,DNAME,LOC) values (1,'������','���l�A');
Insert into HR.DEPT (DEPTNO,DNAME,LOC) values (2,'�޳N��','�䴩');
Insert into HR.DEPT (DEPTNO,DNAME,LOC) values (3,'�]����','�O��');
REM INSERTING into HR.EMP
SET DEFINE OFF;
Insert into HR.EMP (EMPNO,COMM,ENAME,HIREDATE,SAL,DEPTNO,JOBNO,JOB) values (101,8500,'�Ͳ�',to_date('14-5�� -16','DD-MON-RR'),300,3,1,null);
Insert into HR.EMP (EMPNO,COMM,ENAME,HIREDATE,SAL,DEPTNO,JOBNO,JOB) values (4,20000,'�C�C',to_date('08-4�� -16','DD-MON-RR'),3000,2,1,null);
Insert into HR.EMP (EMPNO,COMM,ENAME,HIREDATE,SAL,DEPTNO,JOBNO,JOB) values (5,5000,'�X�_',to_date('28-4�� -16','DD-MON-RR'),2000,2,1,null);
Insert into HR.EMP (EMPNO,COMM,ENAME,HIREDATE,SAL,DEPTNO,JOBNO,JOB) values (1,8000,'angel',to_date('25-4�� -16','DD-MON-RR'),40000,2,2,null);
Insert into HR.EMP (EMPNO,COMM,ENAME,HIREDATE,SAL,DEPTNO,JOBNO,JOB) values (2,11111,'angel',to_date('26-4�� -16','DD-MON-RR'),22222,1,2,null);
REM INSERTING into HR.JOB
SET DEFINE OFF;
Insert into HR.JOB (JOBNO,JOB_TITLE,MAX_SALARY,MIN_SALARY) values (1,'���խ�',1000,100);
Insert into HR.JOB (JOBNO,JOB_TITLE,MAX_SALARY,MIN_SALARY) values (4,'�Ѯv',5000,1000);
Insert into HR.JOB (JOBNO,JOB_TITLE,MAX_SALARY,MIN_SALARY) values (2,'��ߥ�',300,100);
Insert into HR.JOB (JOBNO,JOB_TITLE,MAX_SALARY,MIN_SALARY) values (3,'�U�z',2000,500);
--------------------------------------------------------
--  DDL for Index SYS_C007046
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."SYS_C007046" ON "HR"."DEPT" ("DEPTNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007048
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."SYS_C007048" ON "HR"."EMP" ("EMPNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007050
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."SYS_C007050" ON "HR"."JOB" ("JOBNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table DEPT
--------------------------------------------------------

  ALTER TABLE "HR"."DEPT" ADD PRIMARY KEY ("DEPTNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."DEPT" MODIFY ("DEPTNO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EMP
--------------------------------------------------------

  ALTER TABLE "HR"."EMP" ADD PRIMARY KEY ("EMPNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."EMP" MODIFY ("EMPNO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table JOB
--------------------------------------------------------

  ALTER TABLE "HR"."JOB" ADD PRIMARY KEY ("JOBNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."JOB" MODIFY ("JOBNO" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table EMP
--------------------------------------------------------

  ALTER TABLE "HR"."EMP" ADD CONSTRAINT "FK_46F0187EB1D24FEB8CB39DCA8AF" FOREIGN KEY ("DEPTNO")
	  REFERENCES "HR"."DEPT" ("DEPTNO") ENABLE;
  ALTER TABLE "HR"."EMP" ADD CONSTRAINT "FK_E8A372B26DB64F1285AC4B00C91" FOREIGN KEY ("JOBNO")
	  REFERENCES "HR"."JOB" ("JOBNO") ENABLE;
